### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread

### ISSUE THREAD

**Issue by rahulthawal** [trinketapp/pygame.sk#5]
I followed the instruction as given in the usage. So after you import pygame there is a lag in the message 'success' so I figured it is because of the Synchronous XMLHttpRequest. 

![skulpt-synchronous -request](https://user-images.githubusercontent.com/11020707/33737305-a47181a4-db63-11e7-9b3b-0b2416036974.png)

**Comment by albertjan** [comment]
Yeah probably, it's not a part of this library though. It's skulpt that does the sync loading. And there's a PR currently open for skulpt that will give us the ability to load these async. To combat this in this lib I've made the script that it gets synchronously as small as possible.
