### ISSUE TITLE
Can't import pygame

### ISSUE THREAD

**Issue by sheeeeep** [trinketapp/pygame.sk#8]
This is part of my code: 
```
<script src="./lib/skulpt.js"></script>
<script src="./lib/skulpt-stdlib.js"></script>
<script src="./lib/pygame.js"></script>
```
```
Pygame.init('./lib/skulpt_module');
```
After run `import pygame`，got a message in Console:
`ImportError: No module named pygame on line 1`

I got pygame.js from `npm run build` in master
I got skulpt and skulpt-stdlib from `npm run build` in master of skulpt repo

**Comment by sheeeeep** [comment]
I try to modify some code of pygame.sk to satisfy skulpt's import require:
```
 _extends(Sk.externalLibraries, {
      pygame: {
        path: path + '/__init__.js',
        type: 'js'
      }
    });
```
After these, a new error shows:`unhandled remap type function`

**Comment by sheeeeep** [comment]
I try to fix these problem and get some new problem. Is anything wrong with my usage？

**Comment by albertjan** [comment]
Hi! Just to warn you this not actually an implementation of pygame for skulpt it's just the keyboard event handling bits. We implemented this for the sense hat raspberry pi emulator. 

For this to work you should get trinkets fork of skulpt from here: https://github.com/trinketapp/skulpt-dist

Let me know what happens then. 😄 If it's still broken let me know.

**Comment by sheeeeep** [comment]
Thanks, I will look for other solutions.

**Comment by albertjan** [comment]
Soz
